### ISSUE TITLE
0.9.0 Changelog

### ISSUE THREAD

**Issue by jleclanche** [sddm/sddm#199]
#### New features
- [x] Automatic login has been implemented (through the `AutoUser` config key) (#1)
- [x] The sddm greeter no longer runs as root, but as its own user/group (`sddm` by default). (#116)
- [x] Several systemd/logind compatibility improvements (#188, #192) including support to log to journald (#157). Note that systemd is optional.
- [x] Setting NumLock state on login is now supported through the `Numlock` config key (#66)
- [ ] ~~Initial Wayland support (#153)~~
- [x] Initial support for Plymouth has been added (#198)
#### Removed features
- [x] Dropped "custom session" support as it was too magic and crashy for most users (#220)
#### Bugfixes
- [x] sddm now properly uses PAM, resolving issues with sound and video permissions (#93, #142)
- [x] Improved multi-monitor support (#4, #119)
- [x] Comments are no longer stripped from sddm.conf (#39, #169)
- [x] Now properly using UTF-8 for user names (#178, #179)
- [x] Several packaging and compiling issues have been dealt with (#51, #75, #76, #79, #151, #164, #175, #190)
- [x] The free Oxygen font is now used instead of Geosans Light (#109, #204)
- And many more
#### Documentation
- [x] man pages have been added for `sddm(1)`, `sddm-greeter(1)` and `sddm.conf(5)` (#81, #166)
- [x] `--help` flags are now recognized from the daemon and greeter.
#### Translations
- [x] SDDM is now fully translatable (#84)
- [x] Translations have been added for Simplified Chinese (#99), Czech (#89), Finnish (#96), French (#125), German (#122), Italian (#87), Japanese (#160), Polish (#110), Brazilian and European Portuguese (#91, #102) and Romanian (#98). Thanks, everyone!
